### PR TITLE
Fix potential jetcd-core shading problem

### PR DESCRIPTION
**Pull request by Shawyeok**
### Motivation

There is a potential jar shading issue introduced in #4426 that causes `NoClassDefFoundError` when connecting to an etcd metadata store.

The `jetcd-core-shaded` module was introduced in #4426 to address the compatibility issues between jetcd-core’s grpc-java dependency and Netty. You can find more details [here][1] and in the [grpc-java documentation][2].

[1]: https://github.com/apache/bookkeeper/pull/4426#issuecomment-2162348232
[2]: https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty

Currently, we use `unpack-shaded-jar` execution unpacks the shaded jar produced by `maven-shade-plugin:shade` into the `jetcd-core-shaded/target/classes` directory. However, the classes in this directory conflict with its dependencies. If the `maven-shade-plugin:shade` runs again without cleaning this directory, it can produce an incorrect shaded jar. You can replicate and verify this issue with the following commands:
```shell
# Step 1: Clean the build directory
mvn clean

# Step 2: Perform an install and unpack the shaded jar into a directory.
# Verify the import statement for `io.netty.handler.logging.ByteBufFormat` in 
# `org/apache/pulsar/jetcd/shaded/io/vertx/core/net/NetClientOptions.class`. 
# The correct import should be: 
# `import io.grpc.netty.shaded.io.netty.handler.logging.ByteBufFormat;`.
mvn install
unzip $M2_REPO/org/apache/bookkeeper/metadata/drivers/jetcd-core-shaded/4.18.0-SNAPSHOT/jetcd-core-shaded-4.18.0-SNAPSHOT-shaded.jar \
  -d metadata-drivers/jetcd-core-shaded/target/first-classes

# Step 3: Run the install command again without cleaning.
# The unpacked jar from the previous step will persist in `target/classes`. 
# Unpack the shaded jar into a different directory (e.g., second-classes) and check the import.
# The incorrect import will be: 
# `import io.grpc.netty.shaded.io.grpc.netty.shaded.io.netty.handler.logging.ByteBufFormat;`.
mvn install
unzip $M2_REPO/org/apache/bookkeeper/metadata/drivers/jetcd-core-shaded/4.18.0-SNAPSHOT/jetcd-core-shaded-4.18.0-SNAPSHOT-shaded.jar \
  -d metadata-drivers/jetcd-core-shaded/target/second-classes

# Step 4: Use IntelliJ IDEA's "Compare Directories" tool to compare the `first-classes` 
# and `second-classes` directories. The differences in imports should become apparent.
```

We can remove the attach and unpack configurations, and it should work fine.

This issue has already been [reported][3] in apache/pulsar, and a similar [patch][patch] has addressed it.

[3]: https://github.com/apache/pulsar/issues/23513
[patch]: https://github.com/apache/pulsar/pull/23604

### CODE REVIEW

**Comment by Shawyeok** [comment]
There is a CI test failing, investigating on it.

https://github.com/apache/bookkeeper/actions/runs/11870652415/job/33082639394?pr=4526

**Review by lhotari — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]

File: .github/workflows/bk-ci.yml [hunk 1]
```diff
@@ -242,7 +242,7 @@ jobs:
         run: mvn -B -nsu clean install -Pdocker -DskipTests
 
       - name: Run metadata driver tests
-        run: mvn -B -nsu -f metadata-drivers/pom.xml test -DintegrationTests
+        run: mvn -B -nsu -f metadata-drivers/pom.xml -pl '!jetcd-core-shaded' test -DintegrationTests
```
[the remark this answers is not in the document]
Comment (Shawyeok) [reply .github/workflows/bk-ci.yml:247]: Sure, comment added.

**Review by hezhangjian — APPROVED** [review]
What will our future direction be? Should we wait for a new version of `jetcd-core`?

**Comment by Shawyeok** [comment]
> What will our future direction be? Should we wait for a new version of `jetcd-core`?

@shoothzj 
The maintainer of `jetcd-core` is working on [switch to vertx-grpc-client](https://github.com/etcd-io/jetcd/issues/1372), we could consider change to new version of `jetcd-core` without shading.

**Comment by lhotari** [comment]
> What will our future direction be? Should we wait for a new version of `jetcd-core`?

@shoothzj We have this shading solution in place until jetcd-core is decoupled from grpc-java. grpc-java is tested with a specific Netty version as documented in https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty . If a different Netty version is used, things could break. The jetcd-core-shaded solution transforms the jetcd-core library to use `grpc-netty-shaded`. This PR fixes some issues in the shading configuration.

File: .github/workflows/bk-ci.yml (hunk 1 above)
[the remark this answers is not in the document]
Comment (lhotari) [reply .github/workflows/bk-ci.yml:247]: @Shawyeok I wonder if this should be handled using profiles in `metadata-drivers/pom.xml`? you could exclude `jetcd-core-shaded` in that pom file when `-DintegrationTests` is set by having an integrationTest profile in the file which gets activated with `integrationTests` system property.

[the remark this answers is not in the document]
Comment (Shawyeok) [reply .github/workflows/bk-ci.yml:247]: > you could exclude jetcd-core-shaded in that pom file when -DintegrationTests is set by having an integrationTest profile in the file which gets activated with integrationTests system property.

Cannot do this without step 1.

1. remove `jetcd-core-shaded` module from main part of the pom.xml
2. add a main profile includes all modules, make main profile activate by default
3. add `integrationTests` include all modules except `jetcd-core-shaded `, make `integrationTests` activated with `integrationTests` system property

```diff
Index: metadata-drivers/pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/metadata-drivers/pom.xml b/metadata-drivers/pom.xml
--- a/metadata-drivers/pom.xml	(revision 964b5ed6e7cfa71f50d0c3d5043d4a73c518f795)
+++ b/metadata-drivers/pom.xml	(date 1731916332256)
@@ -27,7 +27,27 @@
     <packaging>pom</packaging>
     <name>Apache BookKeeper :: Metadata Drivers :: Parent</name>
     <modules>
-        <module>jetcd-core-shaded</module>
-        <module>etcd</module>
-    </modules>
+        <module>etcd</module>
+    </modules>
+    <profiles>
+        <profile>
+            <id>integrationTests</id>
+            <activation>
+                <property>
+                    <name>integrationTests</name>
+                </property>
+            </activation>
+            <modules />
+        </profile>
+        <profile>
+            <id>main</id>
+            <activation>
+                <activeByDefault>true</activeByDefault>
+            </activation>
+            <modules>
+                <module>jetcd-core-shaded</module>
+                <module>etcd</module>
+            </modules>
+        </profile>
+    </profiles>
 </project>
```

ref: https://stackoverflow.com/a/8305931/3378901

> Unfortunately, uing the profile you can't exclude a module earlier mentioned in the main <modules> part of the pom.

[the remark this answers is not in the document]
Comment (lhotari) [reply .github/workflows/bk-ci.yml:247]: > Cannot do this without step 1.

Yes, I agree. it might be necessary to move all modules to profiles in the pom.xml . For example, this technique is used in `tests/docker-images/pom.xml` in Pulsar, https://github.com/apache/pulsar/blob/master/tests/docker-images/pom.xml
