### ISSUE TITLE
Compilation warning on unchecked cast

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#537]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

run bookkeeper ci job

- What did you expect to see?

ci passes

- What did you see instead?

the compilation failed due to "unchecked cast" warning.

**Comment by sijie** [comment]
This issue was introduced in #536
